
version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/bradoo_project
    ports:
      - "8000:8000"
    depends_on:
      - database
  database:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=131431
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: