# Generated by Django 3.1.3 on 2021-09-15 17:47

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cnpj', localflavor.br.models.BRCNPJField(max_length=18, unique=True)),
                ('city', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
